### ISSUE TITLE
Making it work on Windows and MacOS

### ISSUE THREAD

**Issue by edraobdu** [edraobdu/printy#1]
We're looking forward to make this application to work on Windows and MacOS. It is currently tested on Unix-like operative systems

**Comment by mihirs16** [comment]
But it does work on Windows (Powershell)..? So do you mean extensive testing of all functionalities? (I thought this project was cool and would want to contribute)

**Comment by edraobdu** [comment]
Hi Mihir, I'm glad to get in touch with you.

I tested yesterday on my Windows 10 virtual machine (I used Debian 10), and it did not work, It seems that we must do some sort of configuration first on the windows shell. Did you test it on your end and it worked? Let me know!

Thanks for forking it, I'll be waiting for you contribution.

As a side note, I'm currently working on a local branch where corrected some errors and rebuilt the format values (it is, each flag won't have the whole escaped value, for instance, '\x1b[31m', but only the number '31', so we can construct the whole escaped value like, lets say for a red bold, '\x1b[31;1m' instead of '\x1b[31m\x1b[1m'.

Also added support for reading from files, for instance: printy(file='path', 'rBH')

And working on another functionality 'inputy', which would extend the input() functionality in this case, for coloring the prompted message, and also allowing to specify a 'type', that is, user would be forced to enter only that type of value (if specified), for instance: inputy('How many?', 'yI', type=int).

I hope finish this feature tomorrow. Looking forward to hear from you.

Thanks!

**Comment by mihirs16** [comment]
Well I just cloned it and thought of giving it a go, to decide where to start in order to port, but on Win 10, Powershell 7.0.0-preview.2 it ran on the python default shell. 

However I only tested the very basic printy('text', 'yBH') and played around with a  couple colors. Should I do an extensive run through all of them?

**Comment by edraobdu** [comment]
Sounds good Mihir. Would you like me to assign this issue to you (after adding you as a contributor)? Let me know!

**Comment by mihirs16** [comment]
Yeah, this seems fun to work on :)

**Comment by edraobdu** [comment]
Great!

**Comment by mihirs16** [comment]
very interestingly.....

It works on the PowerShell opened inside VSCode
![image](https://user-images.githubusercontent.com/44063783/79109329-c19b4900-7d95-11ea-805f-b0c5299fe2ac.png)

but... for Powershell Core, Powershell Preview, Default Powershell and Win CMD
![image](https://user-images.githubusercontent.com/44063783/79109642-5d2cb980-7d96-11ea-82eb-747a0ce492cd.png)

P.S. doesn't work with Git Bash either...

**Comment by edraobdu** [comment]
Hi Mihirs. Interestiong.

Well, I found something that may help us, as I stated before, I think we need to enable this behaviour manually on Windows, check it out:

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

I updated to last version yesterday (v1.1.1), I added some restrictions for non Unix-like, due to it's not working on Windows so far (I haven't test it on OS X though). So, if it's windows, it won't apply any format for now, be aware of that condition.

I think we'd need to run a C script when the platform is Windows, to check the value of the variable ENABLE_VIRTUAL_TERMINAL_PROCESSING.

**Comment by mihirs16** [comment]
But why do we need it, text formatting works otherwise

(for Windows CMD)
![image](https://user-images.githubusercontent.com/44063783/79139727-73f20100-7dd4-11ea-9e5d-cd02bf8e2949.png)


Also works for Powershell and others..

**Comment by edraobdu** [comment]
Oh, gotcha, ok, I was testing it on my Virtual Machine, and I think that's my problem. If you use printy now and it does't show any formats is because of the restriction I set for non Unix-like, but as you said it seems to work. Let me test it on my own on an actual windows machine and see. If I succeed, I'll close this issue, Thanks a lot Mihirs.

Please, if you want, accept the invitation as a contributor I sent to you. I'll update the Contributors.md later.

**Comment by edraobdu** [comment]
We have tested it on 4 different windows machine and it didn't work, perhaps because we're missing the steps that this article points out:

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#example-of-enabling-virtual-terminal-processing

What comes up to my mind is that we can compile that script at the end, to correctly set the flag ENABLE_VIRTUAL_TERMINAL_PROCESSING, and execute it when the platform is Windows only.

Probably you already have that configuration on your console and that's why it is working, I don't really know.

**Comment by mihirs16** [comment]
On each of those 4 machines, do the ANSI escape sequences work? If they do, then we shouldn't have to tamper with console variables. If they don't then we might need to.

**Comment by mihirs16** [comment]
Okay for terminals with disabled processing, we can set the variable at the start.

Is this the behaviour you are looking for?

![image](https://user-images.githubusercontent.com/44063783/79200829-acd1ba80-7e54-11ea-9d33-1a7f8936d43f.png)

The left script is run first, no formatting is understood by the Windows Default Powershell
The right script is run second, formatting is understood by the same.

**Comment by edraobdu** [comment]
Yes!!!! You are awesome man!
It first check whether the console mode is activated or not first right? That was what we needed.

Please add a pull request (not in master branch, but in a new one), if you can add some test for that script that would be awesome too!!

**Comment by edraobdu** [comment]
I was wondering, is that configuration permanent? or is it only for the time the script is running? can you check, please?

**Comment by mihirs16** [comment]
On a <a href="https://github.com/edraobdu/printy/tree/win_vt_enable">separate branch</a>, I have added the console part to core.py:line35.

I have created a branch and pushed a <a href="https://github.com/edraobdu/printy/blob/win_vt_enable/test_enable_virt_term.py">test file</a> to it. 

The current situation is:-
  - W/O importing printy, escape sequences don't work
  - On importing printy:-
      - Escape sequences should work (can be tested with the <a href="https://github.com/edraobdu/printy/blob/win_vt_enable/test_enable_virt_term.py">test file</a>)
      - But the printy function itself still doesn't work... I can't figure out exactly where to put those 
         lines (currently at core.py:line35) please take a look.
      - As for the changes, they only exist until the script is running.

**Comment by edraobdu** [comment]
Yes, the reason it does not work on 'printy' is because I set a restriction on only print the escape sequences on Linux, otherwise it only prints the normal text, without formatting it:

```python
# As of right now, Windows PowerShell and Command line does not apply
# the format to the text without a specific configuration. So we'll
# return the cleaned text for Windows and MacOS operative systems
if self.platform != LINUX:
    text = self._get_cleaned_text(value)
```

I'm gonna create a separate method to handle the script for windows and remove the restriction for windows, after pushing the new version, you can update the library and it should work.

And great, I think that way we are not applying any permanent change to the final user configuration, just for the time it is running. Excellent!!

**Comment by mihirs16** [comment]
Ohhhhh yeah you told me earlier about that restriction ofcourse, silly me I forgot. So that would mean it should (in theory) work when the restriction is lifted?

**Comment by edraobdu** [comment]
Exactly boss, I'm working on a few changes, I already pulled your branch and merged it into my local master, I'll move your test to 'test/' folder (I'll include it in one of the test case though), and then remove the branch from the repository. I'll upload the CONTRIBUTORS.ms and Contributing.md files also.

Thank you so much Mihirs, what an excellent work.

**Comment by mihirs16** [comment]
Thank you sir, I learnt a lot of cool things while exploring this too :) 

P.S. its just Mihir (no 's') xD

**Comment by edraobdu** [comment]
Oh, jaja, yeah, the S is from your last name, sorry, XD

**Comment by edraobdu** [comment]
@all-contributors please add @mihirs16 for tests and code

**Comment by edraobdu** [comment]
@all-contributors please add @edraobdu for code, tests, example, idea, maintenance, doc, bug
@all-contributors please add @farahduk  for idea, code, maintenance

**Comment by edraobdu** [comment]
@all-contributors please add @edraobdu for code, tests, example, idea, maintenance, doc, bug

**Comment by edraobdu** [comment]
@all-contributors please add @farahduk for idea, code, maintenance

**Comment by edraobdu** [comment]
@all-contributors please add @farahduk for idea, code, maintenance

**Comment by edraobdu** [comment]
@all-contributors please add @musicprogram for userTesting
