### ISSUE TITLE
Flag I is not working

### ISSUE THREAD

**Issue by mathcat4** [edraobdu/printy#10]
Hi edraobdu. 
Your printy is the best. I was looking for months for one library which can print colored text in the terminal. <br>
But I have an Issue:
When I tried this code in Python 3.7.7 and in Windows:
```python
from printy import printy
printy("Tanmay", "rI")
```
The Italics style is not working
![Capture](https://user-images.githubusercontent.com/63205558/87021553-a8a80580-c1d5-11ea-9c45-6ce616e55ef9.PNG)
Please help me,
Tanmay

**Comment by edraobdu** [comment]
Hi @Tams-Tams, thank you.

That's weird honestly. Let me check and I'll let you know.

**Comment by willmcgugan** [comment]
Windows terminals don't render italics, I'm afraid. There is work in progress for italics in the new Windows terminal, so maybe we'll see it soon!

**Comment by edraobdu** [comment]
Oh! got it, good to know. Thanks a lot Will!

**Comment by mathcat4** [comment]
Ok thanks.
