### ISSUE TITLE
Adjust the foreground- and highlight color together

### ISSUE THREAD

**Issue by mathcat4** [edraobdu/printy#11]
Hi @edraobdu.
This is not an issue this is more a feature request.
In the printy's documentation, you can highlight the text with a color(eg. `n`):
![image](https://user-images.githubusercontent.com/63205558/87852842-c24bfa00-c905-11ea-9489-601437001dc1.png)

Or you can adjust the foreground color:
![image](https://user-images.githubusercontent.com/63205558/87852861-f4f5f280-c905-11ea-84cd-5b7bca01e2d3.png)

But is there a way you can adjust the foreground- and highlight color toghther?  
Eg. Foreground color is `n` background color is `o`?
regards,
Tanmay

**Comment by edraobdu** [comment]
Hi Tanmay.

I was working on that specific feature right before I launched last release. I was thinking in flags with an underscore for background, like "_b" for a blue background and "<\_b" and "b\_>" for dark and light blue respectively.

But, I thought at the moment that was overcomplicating things, as you can see, that would mess the syntax up a little bit. I wanted to keep printy as simple as posible.

But I think it is a "must have" feature.

I'm gonna keep this issue opened in the meantime.

Thanks!

**Comment by mathcat4** [comment]
@edraobdu 
Just an idea how it cold work (for foreground color green and background color orange). 
In outline formatting: `printy("Text. This colored", "nH{o}"` 
In Inline formatting: `printy("Text. [nH{o}]This@ is colored.")`

**Comment by edraobdu** [comment]
Awesome man. That seems like a good aproach to me, probably the H flag is not necessary. So, anything in between { and }, would be accepted as background color, obviously only color flags (and only one), formats will be rejected.

Thanks for the idea Tams-Tams

**Comment by mathcat4** [comment]
@edraobdu  And if there is nothing between { and } then it works normally as now ```printy("text","nH")```. ;-)

**Comment by edraobdu** [comment]
Hello Tanmay.

New version available including this functionality, thanks for your request.
Printy 2.2.0: [https://pypi.org/project/printy/2.2.0/](https://pypi.org/project/printy/2.2.0/)

![background_printy](https://user-images.githubusercontent.com/31775663/109450286-8ab73b80-7a18-11eb-91b2-e83132a74f94.png)

**Comment by edraobdu** [comment]
@all-contributors please add @Tams-Tams for idea

**Comment by mathcat4** [comment]
Wow, nice! Getting even awesome with the restrictions for inputy!
