### ISSUE TITLE
Can printy handle formatted prints?

### ISSUE THREAD

**Issue by eabase** [edraobdu/printy#12]
Can `printy` also handle formatted prints like: 
```python
#from printy import printy
import printy
name = "[I]Johnny@ [bB]Bold@"
print('Hello {}'.format(name))
```

**Comment by edraobdu** [comment]
![Screenshot_20201103-202358](https://user-images.githubusercontent.com/31775663/98058417-a4ea5f80-1e12-11eb-9a75-4dc5bbdcc645.png)

Yes sir, the string is formatted before printy takes action

**Comment by eabase** [comment]
Nope, not working:

![pwsh_2020-11-05_03-09-10](https://user-images.githubusercontent.com/52289379/98185020-6ccb4580-1f14-11eb-8f36-cbf3c533abd5.png)

**Comment by edraobdu** [comment]
Oh, I see, but you're using 'print' instead 'printy' boss. Try with printy, it should work. Let me know

**Comment by eabase** [comment]
> Oh, I see, but you're using 'print' instead 'printy' boss. Try with printy, it should work. Let me know

Aaah! Yeah, still don't work in Win81, pwsh:
```powershell
python.exe -c "from printy import printy;n='[I]John@ [bB]Bold@';printy('Hello {}'.format(n));"
Hello ←[3mJohn←[0m ←[38;5;20;1mBold←[0m
```
But in a different terminal ok. Cool. Thanks.
