### ISSUE TITLE
overriding the end_format_char

### ISSUE THREAD

**Issue by obentham** [edraobdu/printy#13]
thanks for making a great tool! I just have one request. Could you add an option to `printy()` that allows the `end_format_char` to be manually defined? I'm running into issues where I'm using printy with an f-string, but it's not coloring the output correctly in scenarios where `sent` contains an "@" symbol.

``` python
printy(f'{row_i} [r]lang:@ [n]{lang_name:10}@ [r]clean sent:@ [n]{sent}@')
```

**Comment by edraobdu** [comment]
You're right boss. Actually I ran into the same issue a while ago, haven't had time to work on this though.

I think the option of creating a subclass of printy with custom options is good, but, for this specific problem I guess the best approach to take is to escape whatever we're passing to printy. I'll be updating it with a new helper function that escape all the special characters that printy uses (This way, in case you override and define your own special characters, they will be escaped too).

Probably something like:
```python
from printy import printy, escape_printy as esc

email = 'example@example.com'

printy(f'E-mail: [r]{esc(email)}@')
```

**Comment by edraobdu** [comment]
Hello Oliver.

New version available including this functionality, thanks for your request.
Printy 2.2.0: [https://pypi.org/project/printy/2.2.0/](https://pypi.org/project/printy/2.2.0/)

![escape_printy](https://user-images.githubusercontent.com/31775663/109450367-b89c8000-7a18-11eb-9cb0-1b17b412107b.png)

**Comment by edraobdu** [comment]
@all-contributors please add @obentham for userTesting
