### ISSUE TITLE
Escape didn't escaping square quotes

### ISSUE THREAD

**Issue by kamikadza13** [edraobdu/printy#18]
That cause errors like printy.exceptions.InvalidFlag: 'a' is not a valid flag.
Can you add a solution?

**Comment by edraobdu** [comment]
Hey, sure, can you send me a screenshot with an example of the error please? or a code snippet so I can check it. Thanks a lot!

**Comment by kamikadza13** [comment]
Do not pay attention. I accidentally imported "escape" from html and didn't understand what the problem was. I understand now. Just your message was enough.
