### ISSUE TITLE
What do you think about language sintax highlinghtning?

### ISSUE THREAD

**Issue by edraobdu** [edraobdu/printy#7]
It came to my mind that it could be possible to specify a 'language' or 'lang' parameter, which takes a text and highlight it with the appropriate language syntax.

I'm opening a new branch  for this matter. Any help or ideas are very welcome

**Comment by uhector** [comment]
That would be great, especially for command line based text editors or documentation.

**Comment by edraobdu** [comment]
Exactly sir, I think that's probably the main idea. This is what I've accomplished so far:

Printing this file:

![Screenshot from 2020-04-18 14-31-16](https://user-images.githubusercontent.com/31775663/79669493-78763b00-8181-11ea-8b3e-dfc616324df9.png)

We get:

![Screenshot from 2020-04-18 14-21-18](https://user-images.githubusercontent.com/31775663/79669498-8af07480-8181-11ea-839a-bc6e5130a3cb.png)

Still need to correctly catch the escaped characters, and also working on some key words that are only highlighted within a 'class', like 'self', 'cls' and also the methods '__method_name__'.

Probably tomorrow I'll upload the branch.

**Comment by edraobdu** [comment]
Closing this issue, another library (rich) is handling this matter already and it does it pretty well, I think we should keep printy as a lite and very straight forward library to handle the most common task only.
