### ISSUE TITLE
Have you seen Rich?

### ISSUE THREAD

**Issue by willmcgugan** [edraobdu/printy#9]
Hi, this project has some overlap with a library I’ve been developing (https://github.com/willmcgugan/rich). Just wondering if you’re aware of it. Maybe we could collaborate?

**Comment by edraobdu** [comment]
Hi Will. Mam, that's amazing, that's really impressive. Honestly I wasn't aware.

I was working on a project where I needed exactly that, and, while the research only libraries like colorama or termcolor showed up, so, I decided to make my own one to fill my needs.

Absolutely, we could collaborate, let me take a look to your code and see what I can contribute with.
